<?php
// $Id$

/**
 * @file
 *   A community web interface for Drupal project translation.
 *
 *   Builds on a connector (eg. l10n_drupalorg) and optionally l10n_groups
 *   to provide a convinient web interface for translators to collaborate 
 *   on Drupal project translations.
 */

/**
 * No permission to suggest or translate, just view.
 */
define('L10N_PERM_NONE', 0);

/**
 * Permission to suggest.
 */
define('L10N_PERM_SUGGEST', 1);

/**
 * Permission both to suggest and translate. 
 */
define('L10N_PERM_ALL', 2);

/**
 * Strings with any status.
 */
define('L10N_STATUS_ALL', 0); 

/**
 * Untranslated strings only.
 */
define('L10N_STATUS_UNTRANSLATED', 1); 

/**
 * Has outstanding suggested translations.
 */
define('L10N_STATUS_HAS_SUGGESTION', 2); 

/**
 * Translated (and approved) strings only.
 */
define('L10N_STATUS_TRANSLATED', 3); 

// = Core hooks ================================================================

/**
 * Implementation of hook_help().
 */
function l10n_community_help($section) {
  global $user;
  
  if (!module_exists('l10n_drupalorg') && $section == 'translate') {
    // We don't have an overview page, so fix help path.
    $section = 'translate/languages';
  }
  
  switch ($section) {
    // Help text for language overview start page.
    case 'translate/languages':
      return '<p>'. t('Choose a language to dive in here. There is also a <a href="@by-project-link">by-project listing</a> available, which allows you to dig into languages from the project angle.', array('@by-project-link' => url('translate/projects'))) .'</p>';
    // Help for project overview start page.
    case 'translate/projects':
      return '<p>'. t('Choose a project, and then either export translation templates, or click on the project name to go to the language list to pick a language to translate to. There is also a <a href="@by-language-link">by-language listing</a> available, which allows you to dig into projects from the language angle.', array('@by-language-link' => url('translate/languages'))) .'</p>';
  }
  
  // Match actual translation editing or review pages with the two different path models they could have. 
  if (preg_match('!translate/languages/(?P<langcode>[^/]+)(/(?P<uri>[^/]+)(/(?P<action>import|export))?)?$!', $section, $args) ||
      (preg_match('!translate/projects/(?P<uri>[^/]+)(/(?P<langcode>[^/]+)(/(?P<action>import|export))?)?$!', $section, $args) &&
      !preg_match('!translate/projects/([^/]+)/export$!', $section) &&
      !preg_match('!translate/languages/([^/]+)/import$!', $section))) {
    $perm = isset($args['langcode']) ? l10n_community_get_permission($args['langcode']) : L10N_PERM_NONE;
    $languages = l10n_community_get_languages('name');
    $permission_help = '';
    if (!module_exists('l10n_groups')) {
      // Localization groups is not present so we are dealing with a simple
      // permission model, not a groups based permission scheme. Provide help
      // based on this model. Otherwise l10n_groups provides the extra help.
      switch ($perm) {
        case L10N_PERM_NONE:
          $permission_help = t("You don't have permission to suggest or translate strings, but you can still view the existing translations and export templates or translations for your own use.");
          break;
        case L10N_PERM_SUGGEST:
          $permission_help = t('You can suggest translations and import complete Gettext translation files to suggest more strings at once. People with permission to approve suggestions will be able to either accept or decline your suggestions. Feel free to export translation templates, or the current state of the translation if you are more comfortable working offline.');
          break;
        case L10N_PERM_ALL:
          $permission_help = t('As a fully empowered user, you can suggest translations as well as approve translations suggested by others. Export/import of Gettext translation files is also possible.');
          break;
      }
      $permission_help = '<p>'. $permission_help .'</p>';
    }

    // Now construct the actual help text depending on whether we have project or language values from the address. 
    if (isset($args['action'])) {
      // We have an import or export action. 
      switch ($args['action']) {
        case 'import':
          return '<p>'. t('Because all project translations are shared, although you import this file for this project, it might provide translations for strings used in other projects too. This means that your actions can have impact easily on other project translations too.') .'</p>'. $permission_help;
        case 'export':
          return '<p>'. t('You have two different options to export. You can either export a template package for this project, or a package containing the existing translations for a given release. Both types will use the GNU Gettext Portable Object (Template) format, which is understood by Drupal and desktop translation editing tools.') .'</p>'. $permission_help;
      }
    }
    else {
      // We are on some overview page.
      if (!isset($args['uri'])) {
        // Only language code is present => project list is shown.
        $output = '<p>'. t('This page shows a list of all projects and their overall translation status in this language (accumulated for all releases).') .'</p>'. $permission_help;
        return $output;
      }
      elseif (!isset($args['langcode'])) {
        // Only project code is present => language list is shown.
        $output = '<p>'. t('This page shows a list of all languages and their overall translation status (accumulated for all releases). Exporting translation works for all languages. Importing your translations is only possible to languages where you have sufficient privileges to do so.') .'</p>';
        return $output;
      }
      else {
        // Language code and project both present.
        return $permission_help;
      }
    }
  }
}

/**
 * Implementation of hook_menu().
 *
 * Note that all menu items are accessible to anyone, because
 * all functionality can be presented in a view-only form, which
 * anonymous users should be able to browse.
 */
function l10n_community_menu($may_cache) {
  $items = array();
  if ($may_cache) {
    // Main menu items (cacheable). These are a small number of items, and
    // they are always the same, so we are safe to cache them.
    if (!module_exists('l10n_drupalorg')) {
      // These are defined differently by l10n_drupalorg to provide an
      // additional overview for translators.
      $items[] = array(
        'title' => t('Translate projects'),
        'path' => 'translate',
        'callback' => 'l10n_community_page_wrapper',
        'callback arguments' => array('pages', 'l10n_community_overview_languages'),
        'access' => TRUE,
      );
      $items[] = array(
        'title' => t('By language'),
        'description' => t('Overview of languages and their translation status.'),
        'path' => 'translate/languages',
        'access' => TRUE,
        'type' => MENU_DEFAULT_LOCAL_TASK,
        'weight' => -10,
      );
    }
    $items[] = array(
      'title' => t('By project'),
      'description' => t('Overview of projects and their translation status.'),
      'path' => 'translate/projects',
      'callback' => 'l10n_community_page_wrapper',
      'callback arguments' => array('pages', 'l10n_community_overview_projects'),
      'access' => TRUE,
      'type' => MENU_LOCAL_TASK,
      'weight' => -5,
    );
    $items[] = array(
      'path' => 'translate/projects/autocomplete',
      'title' => t('Project autocomplete'),
      'callback' => 'l10n_community_projects_autocomplete',
      'access' => TRUE,
      'type' => MENU_CALLBACK
    );
  }
  
  // Non-cachable menu items. These are numerous to generate for all languages and all projects,
  // so we are not caching them, and only generate on demand, when they are in need.    
  elseif (arg(0) == 'translate') {
    // AJAX callbacks for easy translation management.
    $items[] = array(
      'title' => t('String details'),
      'path' => 'translate/details',
      'callback' => 'l10n_community_page_wrapper',
      'callback arguments' => array('ajax', 'l10n_community_string_details'),
      'access' => TRUE,
      'type' => MENU_CALLBACK,
    );
    $items[] = array(
      'title' => t('Approve suggestion'),
      'path' => 'translate/approve',
      'callback' => 'l10n_community_page_wrapper',
      'callback arguments' => array('ajax', 'l10n_community_string_approve'),
      'access' => TRUE,
      'type' => MENU_CALLBACK,
    );
    
    drupal_add_css(drupal_get_path('module', 'l10n_community') .'/l10n_community.css', 'module');

    if (arg(1) == 'languages') {
      // Either a language overview screen or the user already choose a language.
      if (($langcode = arg(2)) && ($languages = l10n_community_get_languages('name')) && isset($languages[$langcode])) {
        // There is a valid language already choosen.
        $items[] = array(
          'title' => $languages[$langcode],
          'description' => t('Projects and their translation status.'),
          'path' => 'translate/languages/' . $langcode,
          'callback' => 'l10n_community_page_wrapper',
          'callback arguments' => array('pages', 'l10n_community_status_projects', $langcode),
          'access' => TRUE,
          'type' => MENU_CALLBACK,
        );
        $items[] = array(
          'title' => t('Import'),
          'path' => 'translate/languages/' . $langcode .'/import',
          'callback' => 'l10n_community_page_wrapper',
          'callback arguments' => array('import', 'l10n_community_import_page', $langcode),
          'type' => MENU_CALLBACK,
        );
        if (($uri = arg(3)) && ($projects = l10n_community_get_projects()) && isset($projects[$uri])) {
          // Menu items for project listing based on language.
          $items[] = array(
            'title' => t('Translate'),
            'path' => 'translate/languages/' . $langcode .'/'. $uri,
            'callback' => 'l10n_community_page_wrapper',
            'callback arguments' => array('pages', 'l10n_community_translate_page', $langcode, $uri),
            'access' => TRUE,
            'type' => MENU_CALLBACK,
          );
          // Tabs to translate, import and export projects.
          $items[] = array(
            'title' => t('Translate'),
            'path' => 'translate/languages/' . $langcode .'/'. $uri .'/translate',
            'type' => MENU_DEFAULT_LOCAL_TASK,
            'weight' => -10,
          );
          $items[] = array(
            'title' => t('Import'),
            'path' => 'translate/languages/' . $langcode .'/'. $uri .'/import',
            'callback' => 'l10n_community_page_wrapper',
            'callback arguments' => array('import', 'l10n_community_import_page', $langcode, $uri),
            'type' => MENU_LOCAL_TASK,
            'weight' => -5,
            'access' => l10n_community_get_permission($langcode) != L10N_PERM_NONE,
          );
          $items[] = array(
            'title' => t('Export'),
            'path' => 'translate/languages/' . $langcode .'/'. $uri .'/export',
            'callback' => 'l10n_community_page_wrapper',
            'callback arguments' => array('export', 'l10n_community_export_page', $uri, $langcode),
            'type' => MENU_LOCAL_TASK,
            'weight' => 0,
          );
        }
      }
    }
    
    elseif (arg(1) == 'projects') {
      if (($uri = arg(2)) && ($projects = l10n_community_get_projects()) && isset($projects[$uri])) {
        // We have a valid project name from the web address.
        $items[] = array(
          'title' => $projects[$uri]->title,
          'description' => t('Languages and their translation status.'),
          'path' => 'translate/projects/' . $uri,
          'callback' => 'l10n_community_page_wrapper',
          'callback arguments' => array('pages', 'l10n_community_status_languages', $uri),
          'access' => TRUE,
          'type' => MENU_CALLBACK,
        );
        $items[] = array(
          'title' => t('Export template'),
          'path' => 'translate/projects/' . $uri .'/export',
          'callback' => 'l10n_community_page_wrapper',
          'callback arguments' => array('export', 'l10n_community_export_page', $uri),
          'type' => MENU_CALLBACK,
        );
        if (($langcode = arg(3)) && ($languages = l10n_community_get_languages('name')) && isset($languages[$langcode])) {
          // Menu item for language listing based on project.
          $items[] = array(
            'title' => t('Translate'),
            'path' => 'translate/projects/' . $uri .'/'. $langcode,
            'callback' => 'l10n_community_page_wrapper',
            'callback arguments' => array('pages', 'l10n_community_translate_page', $langcode, $uri),
            'access' => TRUE,
            'type' => MENU_CALLBACK,
          );
          // Tabs to translate, import and export projects.
          $items[] = array(
            'title' => t('Translate'),
            'path' => 'translate/projects/' . $uri .'/'. $langcode .'/translate',
            'type' => MENU_DEFAULT_LOCAL_TASK,
            'weight' => -10,
          );
          $items[] = array(
            'title' => t('Import'),
            'path' => 'translate/projects/' . $uri .'/'. $langcode .'/import',
            'callback' => 'l10n_community_page_wrapper',
            'callback arguments' => array('import', 'l10n_community_import_page', $langcode, $uri),
            'type' => MENU_LOCAL_TASK,
            'weight' => -5,
            'access' => l10n_community_get_permission($langcode) != L10N_PERM_NONE,
          );
          $items[] = array(
            'title' => t('Export'),
            'path' => 'translate/projects/' . $uri .'/'. $langcode .'/export',
            'callback' => 'l10n_community_page_wrapper',
            'callback arguments' => array('export', 'l10n_community_export_page', $uri, $langcode),
            'type' => MENU_LOCAL_TASK,
            'weight' => 0,
          );
        }
      }
    }
    else {
      // Displaying the translation overview page. This is used to present admin page like panels.
      drupal_add_css(drupal_get_path('module', 'system') .'/admin.css', 'module');
    }
  }
  return $items;
}

/**
 * Implementation of hook_perm().
 */
function l10n_community_perm() {
  return array('submit suggestions', 'submit translations and approve suggestions');
}

/**
 * Implementation of hook_block().
 *
 * Guide users on the special chars in translatables.
 */
function l10n_community_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      $blocks = array(
        0 => array(
          'info' => t('Translation help'),
          'weight' => 0,
          'enabled' => 1,
          'region' => 'left'
        )
      );
      return $blocks;
    
    case 'view':
      // Named patterns used to support two URL forms and import/export action screens. See hook_help for information.
      if (preg_match('!translate/languages/(?P<langcode>[^/]+)/(?P<uri>[^/]+)!', $_GET['q'], $args) ||
          (preg_match('!translate/projects/(?P<uri>[^/]+)/(?P<langcode>[^/]+)!', $_GET['q'], $args) &&
          !preg_match('!translate/projects/([^/]+)/export!', $_GET['q']) &&
          !preg_match('!translate/languages/([^/]+)/import!', $_GET['q']))) {
        // Only show block if we have valuable and relevant information there.
        $languages = l10n_community_get_languages();
        $items = array();
        $items[] = t('!newline_image represents a line break. Remember to include a line break in the same position in the translation. Beginning and ending line breaks are saved properly, even if you miss to include them.', array('!newline_image' => ' <img src="'. base_path() . drupal_get_path('module', 'l10n_community') .'/images/newline.png" alt="'. t('Newline marker') . '" /> '));
        $items[] = t('Variables are designated with !, @ and % (like %example, !example or @example), and should be kept in the translated text as-is.');
        $formula = join(' ', preg_split('!(&&|\\|\\||%|<=|>=|==|\\!=|\\?|:)!', $languages[$args['langcode']]->formula, -1, PREG_SPLIT_DELIM_CAPTURE));
        $items[] = t('The plural formula in use with this language is %formula.', array('%formula' => str_replace('$n', 'n', $formula)));
        return array(
          'subject' => t('Translation help'),
          'content' => theme('item_list', $items),
        );
      }
  }
}

// = Status pages ==============================================================

/**
 * Wrapper function for functionality implemented outside this module.
 *
 * The functionality implemented here is native to Drupal 6.
 */
function l10n_community_page_wrapper() {
  $args = func_get_args();
  $filename = array_shift($args);
  $function = array_shift($args);
  include_once drupal_get_path('module', 'l10n_community') .'/'. $filename .'.inc';
  return call_user_func_array($function, $args);
}

// = API functions =============================================================

/**
 * Helper function for language listing.
 *
 * @param $key
 *   Key name to restrict return value to.
 * @return
 *   If null, a list of language objects is returned, keyed by language code.
 *   Otherwise values referenced by $key are returned, keyed by language code.
 */
function l10n_community_get_languages($key = NULL) {
  static $languages = NULL;
  
  if (!isset($languages)) {
    $result = db_query("SELECT * FROM {locales_meta} WHERE locale != 'en' ORDER BY name ASC");
    $languages = array();
    while ($language = db_fetch_object($result)) {
      $languages[$language->locale] = $language;
    }
  }
  
  if (isset($key)) {
    // Build list of values with the specific key, if asked.
    $result = array();
    foreach ($languages as $language) {
      $result[$language->locale] = $language->$key;
    }
    return $result;
  }
  else {
    // Return full object list otherwise.
    return $languages;
  }
}

/**
 * Get translation permission level for a specific user.
 *
 *
 * @param $langcode
 *   Language code, for example 'hu', 'pt-br', 'de' or 'it'.
 * @param $account
 *   Optional user account.
 * @return
 *   L10N_PERM_NONE, L10N_PERM_SUGGEST or L10N_PERM_ALL
 */
function l10n_community_get_permission($langcode, $account = NULL) {
  static $permissions = array();
  global $user;
  
  if (empty($langcode)) {
    return L10N_PERM_NONE;
  }
  if (!isset($account)) {
    $account = $user;
  }
  
  if (isset($permissions[$account->uid][$langcode])) {
    // Return cached value if available.
    return $permissions[$account->uid][$langcode];
  }
  
  // Initialize to lowest possible permission.
  $permissions[$account->uid][$langcode] = L10N_PERM_NONE;
  
  if ($account->uid == 1) {
    // The administrator has all permissions in all languages.
    return ($permissions[$account->uid][$langcode] = L10N_PERM_ALL);
  }
  
  $global_permission = user_access('submit translations and approve suggestions', $account) ? L10N_PERM_ALL : (user_access('submit suggestions', $account) ? L10N_PERM_SUGGEST : L10N_PERM_NONE);
  
  if (($global_permission != L10N_PERM_NONE) && module_exists('l10n_groups')) {
    // Fill up permission information for this account if it has any permission.
    l10n_groups_get_permission($permissions, $global_permission, $langcode, $account);
  }
  else {
    // Remember global permission if using l10n_community standalone.
    $permissions[$account->uid][$langcode] = $global_permission;
  }
  
  // Return from local cache.
  return $permissions[$account->uid][$langcode];
}

/**
 * Provides a list of projects from the database, ordered by uri.
 *
 * @param $uri
 *   Project URI, if requesting information about one project only.
 *   If not specified, information about all projects is returned.
 * @param $pager
 *   Number of projects to return a pager query result with. If NULL,
 *   all projects are returned.
 * @return
 *   An associative array keyed with project uris.
 */
function l10n_community_get_projects($uri = NULL, $pager = NULL) {
  static $projects = array();
  
  if (isset($pager)) {
    // If a pager view was asked for, collect data independently.
    $results = pager_query('SELECT * FROM {l10n_community_project} ORDER BY uri', $pager, 0, NULL);
    $pager_results = array();
    while ($project = db_fetch_object($results)) {
      $pager_results[$project->uri] = $project;
      // Save project information for later, if someone asks for it by uri.
      $projects[$project->uri] = $project;
    }
    return $pager_results;
  }
  else {
    if (isset($uri)) {
      // A specific project was asked for.
      if (isset($projects[$uri])) {
        // Can be served from the local cache.
        return $projects[$uri];
      }
      // Not found in cache, so query and cache before returning.
      $result = db_query("SELECT * FROM {l10n_community_project} WHERE uri = '%s'", $uri);
      if ($project = db_fetch_object($result)) {
        $projects[$uri] = $project;
        return $project;
      }
    }
    else {
      // A list of *all* projects was asked for.
      $results = db_query('SELECT * FROM {l10n_community_project} ORDER BY uri');
      while ($project = db_fetch_object($results)) {
        $projects[$project->uri] = $project;
      }
      return $projects;
    }
  }
}

/**
 * Get all releases of a project.
 *
 * @param $uri
 *   Project code to look up releases for.
 * @param $parsed_only
 *   If TRUE, only releases which already have their tarballs downloaded and
 *   parsed for translatables are returned. Otherwise all releases recorded in
 *   the database are returned.
 * @return
 *   Array of release objects for project, keyed by release id.
 */
function l10n_community_get_releases($uri, $parsed_only = TRUE) {
  $releases = array();
  $query = "SELECT r.* FROM {l10n_community_release} r LEFT JOIN {l10n_community_project} p ON r.pid = p.pid WHERE p.uri = '%s'";
  if ($parsed_only) {
    $query .= ' AND r.last_parsed > 0';
  }
  $result = db_query($query, $uri);
  while ($release = db_fetch_object($result)) {
    $releases[$release->rid] = $release;
  }
  return $releases;
}

/**
 * Get strings under some conditions.
 *
 * @param $project
 *   Project object to look up strings for.
 * @param $langcode
 *   Language code to use for the lookup.
 * @param $status
 *   Filter strings by status. See L10N_STATUS_ALL,
 *   L10N_STATUS_UNTRANSLATED, L10N_STATUS_HAS_SUGGESTION and
 *   L10N_STATUS_TRANSLATED.
 * @param $release
 *   Release id of the particular project release to filter with.
 *   Use NULL to not filter on releases.
 * @param $search
 *   Substring to search for in all source and translation strings.
 * @param $pager
 *   Number of strings to be returned in a pager. Should be NULL if
 *   no pager should be used.
 * @return
 *   An array of string records from database.
 */
function l10n_community_get_strings($project, $langcode, $status = L10N_STATUS_ALL, $release = NULL, $search = NULL, $pager = NULL) {
  
  $sql = $sql_count = '';
  $sql_args = array();
  
  // Project and language based filtering built in.
  $sql = "SELECT DISTINCT s.sid, s.value, t.tid, t.language, t.translation, t.uid_entered, t.uid_approved, t.time_entered, t.time_approved, t.has_suggestion, t.is_suggestion, t.is_active FROM {l10n_community_release} r INNER JOIN {l10n_community_file} f ON r.rid = f.rid INNER JOIN {l10n_community_line} l ON f.fid = l.fid INNER JOIN {l10n_community_string} s ON l.sid = s.sid LEFT JOIN {l10n_community_translation} t ON s.sid = t.sid AND t.language = '%s' AND t.is_active = 1 AND t.is_suggestion = 0 WHERE r.pid = %d";
  $sql_count = "SELECT COUNT(DISTINCT(s.sid)) FROM {l10n_community_release} r INNER JOIN {l10n_community_file} f ON r.rid = f.rid INNER JOIN {l10n_community_line} l ON f.fid = l.fid INNER JOIN {l10n_community_string} s ON l.sid = s.sid LEFT JOIN {l10n_community_translation} t ON s.sid = t.sid AND t.language = '%s' AND t.is_active = 1 AND t.is_suggestion = 0 WHERE r.pid = %d";
  $sql_args = array($langcode, $project->pid);

  if (!empty($search)) {
    // Search in the source or target strings.
    $sql_args[] = $search;
    $sql_args[] = $search;
    $search_sql = " AND (s.value LIKE '%%%s%%' OR t.translation LIKE '%%%s%%')";
    $sql .= $search_sql;
    $sql_count .= $search_sql;
  }

  if (isset($release)) {
    // Release restriction.
    $sql_args[] = $release;
    $sql_args[] = $release;
    $release_sql = ' AND r.rid = %d';
    $sql .= $release_sql;
    $sql_count .= $release_sql;
  }
    
  // Restriction based on string status.
  switch ($status) {
    case L10N_STATUS_UNTRANSLATED:
      // We are doing a LEFT JOIN especially to look into the case, when we have nothing 
      // to match in the translation table, but we still have the string. (We get our 
      // records in the result set in this case). The translation field is empty or
      // NULL in this case, as we are not allowing NULL there and only saving an empty
      // translation if there are suggestions but no translation yet.
      $status_sql = " AND (t.translation is NULL OR t.translation = '')";
      $sql .= $status_sql;
      $sql_count .= $status_sql;
      break;
    case L10N_STATUS_TRANSLATED:
      $status_sql = " AND t.translation != ''";
      $sql .= $status_sql;
      $sql_count .= $status_sql;
      break;
    case L10N_STATUS_HAS_SUGGESTION:
      // Note that we are not searching in the suggestions themselfs, only
      // the source and active translation values. The user interface underlines
      // that we are  looking for strings which have suggestions, not the
      // suggestions themselfs.
      $status_sql = " AND t.has_suggestion = 1";
      $sql .= $status_sql;
      $sql_count .= $status_sql;
      break;
    case L10N_STATUS_ALL:
    default:
      // Leave query alone on this case.
      break;
  }

  // We either need a pager or a full result.
  if (isset($pager)) {
    $strings = pager_query($sql, $pager, 0, $sql_count, $sql_args);
  }
  else {
    $strings = db_query($sql, $sql_args);
  }
  $result = array();
  while ($string = db_fetch_object($strings)) {
    $result[] = $string;
  }
  return $result;
}

/**
 * Get string counts for summaries.
 *
 * @param $type
 *   Type of string count to return:
 *     - all:       count of all strings
 *     - project:   count of strings in one project (identified by $id)
 *     - languages: array of the count of translated strings and suggestions by langcode
 *     - projects:  array of the count of translated strings and suggestions by pid
 * @param $id
 *   The project id when the 'project' type is used. The result set can be
 *   restricted by an ID from the oppposing type for the later two types.
 *   Eg. 'projects' summaries can be restricted to one specific language, or
 *   'languages' summeries can be restricted to one specific project. This
 *   id represents the identifier (pid or langcode) of the restricting item.
 *   For the 'all' type, this value is discarded.
 *
 * @todo
 *   These queries are *slooow*. The query cache helps a lot with caching the
 *   result, so the slowness only shows for the first run, but still it would
 *   be good to look into optimizing these.
 */
function l10n_community_get_string_count($type, $id = NULL) {
  switch ($type) {
    case 'all':
      // Return a count of all strings.
      return db_result(db_query("SELECT COUNT(sid) FROM {l10n_community_string}"));
    
    case 'project':
      // Return a count of all strings in this project, id required.
      return db_result(db_query('SELECT COUNT(DISTINCT s.sid) FROM {l10n_community_release} r INNER JOIN {l10n_community_file} f ON r.rid = f.rid INNER JOIN {l10n_community_line} l ON f.fid = l.fid INNER JOIN {l10n_community_string} s ON l.sid = s.sid WHERE r.pid = %d', $id));
    
    case 'languages':
      // Summeries based on language codes, restricted to a specific project if $id is set.
      $sums = array();
      if (!isset($id)) {
        // Simple count query if we are not filtering by project.
        $count_sql = 'SELECT COUNT(t.sid) translation_count, t.language, t.is_suggestion FROM {l10n_community_string} s LEFT JOIN {l10n_community_translation} t ON s.sid = t.sid WHERE t.is_active = 1 AND t.translation != "" GROUP BY t.language, t.is_suggestion';
      }
      else {
        // Rather complex join if we also need to factor the project in.
        $count_sql = 'SELECT COUNT(DISTINCT t.sid) translation_count, t.language, t.is_suggestion FROM {l10n_community_release} r INNER JOIN {l10n_community_file} f ON r.rid = f.rid INNER JOIN {l10n_community_line} l ON f.fid = l.fid INNER JOIN {l10n_community_string} s ON l.sid = s.sid LEFT JOIN {l10n_community_translation} t ON s.sid = t.sid WHERE r.pid = %d AND t.is_active = 1 AND t.translation != "" GROUP BY t.language, t.is_suggestion';
      }
      $result = db_query($count_sql, $id);
      while ($row = db_fetch_object($result)) {
      	if (!isset($sums[$row->language])) {
      	  // Set default zeroes for summaries.
          $sums[$row->language] = array(0, 0);
      	}
        // Fill in the 0 or 1 element based on whether we have a result
        // for suggestions or translations.
        $sums[$row->language][(int) $row->is_suggestion] = $row->translation_count;
      }
      return $sums;
      break;
    
    case 'projects':
      // Get summaries by projects. Restricted to a specific language, if $id is set.
      
      // First get the count of strings available for translation.
      $sums = $count_args = array();
      $result = db_query("SELECT COUNT(DISTINCT s.sid) string_count, r.pid FROM {l10n_community_release} r INNER JOIN {l10n_community_file} f ON r.rid = f.rid INNER JOIN {l10n_community_line} l ON f.fid = l.fid INNER JOIN {l10n_community_string} s ON l.sid = s.sid GROUP BY r.pid;");
      while ($row = db_fetch_object($result)) {
        // Initialize remaining fields to zeroes too.
        $sums[$row->pid] = array($row->string_count, 0, 0);
      }
      // Get the count of distinct strings translated and suggestions per project.
      $count_sql = 'SELECT COUNT(DISTINCT t.sid) translation_count, r.pid, t.is_suggestion FROM {l10n_community_release} r INNER JOIN {l10n_community_file} f ON r.rid = f.rid INNER JOIN {l10n_community_line} l ON f.fid = l.fid INNER JOIN {l10n_community_string} s ON l.sid = s.sid LEFT JOIN {l10n_community_translation} t ON s.sid = t.sid WHERE t.is_active = 1 AND t.translation != "" ';
      if (isset($id)) {
        // Limit to language if desired.
        $count_sql .= "AND t.language = '%s' ";
        $count_args[] = $id;
      }
      $count_sql .= 'GROUP BY r.pid, t.is_suggestion';
      $result = db_query($count_sql, $count_args);
      while ($row = db_fetch_object($result)) {
        // Fill up the zero spots we added above with real data.
        $sums[$row->pid][((int) $row->is_suggestion) + 1] = $row->translation_count;
      }
      return $sums;
  }
}

/**
 * Save a translated string into database.
 *
 * @param $sid
 *   Source string identifier.
 * @param $translation
 *   The translation string.
 * @param $langcode
 *   Language code, for example: 'hu', 'pt-br', 'de', 'it' and so on.
 * @param $uid
 *   User ID.
 * @param $suggestion
 *   TRUE if $translation is a suggestion, FALSE otherwise.
 * @param $inserted
 *   Counter to increment if insert is made.
 * @param $updated
 *   Counter to increment if update is made.
 * @param $unchanged
 *   Counter to increment if nothing is changed.
 * @param $suggested
 *   Counter to increment if a suggestion was saved.
 *
 * @todo
 *   Take care of trailing and leading whitespace.
 * @todo
 *   Note that we are not tracking if the user entered something which
 *   was an existing active suggestion, in which case a new suggestion
 *   is added. This is an edge case, but possibly not desired.
 */
function l10n_community_target_save($sid, $translation, $langcode, $uid, $suggestion, &$inserted, &$updated, &$unchanged, &$suggested) {
  
  // Look for an existing active translation.
  $existing_string = db_fetch_object(db_query("SELECT sid, tid, translation FROM {l10n_community_translation} WHERE sid = %d AND language = '%s' AND is_suggestion = 0 AND is_active = 1", $sid, $langcode));
  
  if (isset($existing_string->sid)) {
    // We have an active translation.
    if ($existing_string->translation != $translation) {
      // And what we should save now is different.
      if ($suggestion) {
        // Saving a suggestion, so set flag on translation.
        db_query("UPDATE {l10n_community_translation} SET has_suggestion = 1 WHERE tid = %d", $existing_string->tid);
        $suggested++;
      }
      else {
        // Saving a different translation -> deactivate previous translations and suggestions.
        db_query("UPDATE {l10n_community_translation} SET is_active = 0 WHERE sid = %d AND language = '%s';", $sid, $langcode);
        $updated++;
      }
      db_query("INSERT INTO {l10n_community_translation} (sid, translation, language, uid_entered, time_entered, uid_approved, time_approved, is_suggestion, is_active) VALUES (%d, '%s', '%s', %d, %d, %d, %d, %d, 1)", $sid, $translation, $langcode, $uid, time(), ($suggestion ? 0 : $uid), ($suggestion ? 0 : time()), $suggestion);
    }
    else {
      // Same string as existing translation. 
      $unchanged++;
    }
  }
  
  else {
    // No active translation exists.
    if ($suggestion) {
      // No translation yet -> INSERT empty placeholder so we can track suggestions.
      db_query("INSERT INTO {l10n_community_translation} (sid, translation, language, uid_entered, time_entered, has_suggestion, is_active) VALUES (%d, '', '%s', 0, %d, 1, 1)", $sid, $langcode, time());
      db_query("INSERT INTO {l10n_community_translation} (sid, language, translation, uid_entered, time_entered, is_suggestion, is_active) VALUES (%d, '%s', '%s', %d, %d, 1, 1)", $sid, $langcode, $translation, $uid, time());
      $suggested++;
    }
    else {
      // No active translation yet -> INSERT.
      db_query("INSERT INTO {l10n_community_translation} (sid, translation, language, uid_entered, time_entered, is_active) VALUES (%d, '%s', '%s', %d, %d, 1)", $sid, $translation, $langcode, $uid, time());
      $inserted++;
    }
  }
}

/**
 * Set a message based on the number of translations changed.
 * 
 * Used by both the save and import process.
 */
function l10n_community_update_message($inserted, $updated, $unchanged, $suggested) {
  // Inform user about changes made.
  $message = array();
  if ($inserted) {
    $message[] = format_plural($inserted, '1 new translation added', '@count new translations added');
  }
  if ($suggested) {
    $message[] = format_plural($suggested, '1 new suggestion added', '@count new suggestions added');
  }
  if ($updated) {
    $message[] = format_plural($updated, '1 translation updated', '@count translations updated');
  }
  if ($unchanged) {
    $message[] = format_plural($unchanged, '1 translation unchanged', '@count translations unchanged');
  }
  if (count($message)) {
    drupal_set_message(join(', ', $message) .'.');
  }
}

/**
 * Detect major version number for given project file.
 *
 * @param $path
 *   Either a file name or a path to a file, containing the file name.
 * @return
 *   A number with the major version of the project file, computed from
 *   the version portion of the filename.
 *     - 4 for 4.x versions (even 4.6.x. and 4.7.x)
 *     - 5 for 5.x versions
 *     - 6 for 6.x versions
 */
function l10n_community_detect_major_version($path) {
  // Only interested in the filename.
  $filename = basename($path);
  // The project name could not contain hyphens, as the project name equals
  // function name prefixes, and hyphens are not allowed in function names.
  list ($project_name, $version) = explode('-', $filename);
  // The major number is the first digit (eg. 6 for 6.x-dev, 4 for 4.7.x).
  return (int) $version;
}

/**
 * Does the given file path point to a package with a supported major version?
 *
 * @param $path
 *   Either a file name or a path to a file, containing the file name.
 * @return
 *   TRUE if the major version is supported, FALSE otherwise.
 */
function l10n_community_is_supported_version($path) {
  // Only Drupal 5.x and 6.x projects are supported.
  return in_array(l10n_community_detect_major_version($path), array(5, 6));
}

/**
 * Retrieve a pipe delimited string of autocomplete suggestions for projects.
 */
function l10n_community_projects_autocomplete($string = '') {
  $matches = array();
  if ($string) {
    $result = db_query_range("SELECT title FROM {l10n_community_project} WHERE LOWER(title) LIKE LOWER('%s%%')", $string, 0, 10);
    while ($project = db_fetch_object($result)) {
      $matches[$project->title] = check_plain($project->title);
   }
  }
  print drupal_to_js($matches);
  exit();
}
