<?php
// $Id$

/**
 * @file
 *   File used purely to test the database backend of l10n_server.
 *
 *   Not a real module, so lacks .info files and such to not pollute the
 *   user interface of the host website. Cannot be enabled and there would
 *   be no point either.
 */

/**
 * Implementation of hook_menu()
 */
function l10n_test_menu() {
  $items = array();
  $items['translate/test'] = array(
    'title' => 'Test menu item',
    'description' => 'This is a test menu item',
    'page callback' => 'l10n_test_page',
  );
  return $items;
}

function l10n_test_page() {
  $output = t('This is a test string.');
  $output .= format_plural($count, '1 test string', '@count test strings');
}
